# https://github.com/realm/SwiftLint#configuration

disabled_rules:
    - cyclomatic_complexity
    - file_length
    - function_body_length
    - function_parameter_count
    - notification_center_detachment
    - type_body_length
    - force_unwrapping

opt_in_rules:
    - force_unwrapping

identifier_name:
    excluded:
        - id
        - db

excluded:
    - Pods
    # Code from web
    - ExponeaSDK/ExponeaSDK/Classes/Others/Reachability.swift
    # Code from web
    - ExponeaSDK/ExponeaSDK/Classes/Others/NSManagedObjectContext+Perform.swift
