# This GitHub Actions workflow syncs Markdown files to the Bloomreach production documentation site.
name: ReadMe Production GitHub Action 🦉

on:
  push:
    branches:
      # This workflow will run every time you push code to the following branch: `main`
      # Check out GitHub's docs for more info on configuring this:
      # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows
      - main

jobs:
  rdme-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run `docs` command 🚀
        uses: readmeio/rdme@v8
        with:
          rdme: docs Documentation --key=${{ secrets.README_PRODUCTION_API_KEY }} --version=2
